### ISSUE TITLE
Possible bug in source code (CWE-480)

### ISSUE THREAD

**Issue by AppChecker** [atutor/ATutor#130]
Hello!

We've checked your code with [AppChecker static analyzer](https://cnpo.ru/en/solutions/appchecker.php) and found possible bug:

https://github.com/atutor/ATutor/blob/ded49bdfdb7068be63cdcf06038f69a111e138c8/themes/mobile/admin/index.tmpl.php#L1
https://github.com/atutor/ATutor/blob/ded49bdfdb7068be63cdcf06038f69a111e138c8/themes/simplified_desktop/admin/index.tmpl.php#L1

```
<?php global $_config; $_config_defaults;?>
```
$_config_defaults is not in global section, it's on its own.

Possible defect was found by Echelon Team with [AppChecker static analyzer](https://cnpo.ru/en/solutions/appchecker.php)

**Comment by atutor** [comment]
Thanks for that. Seems to be old code now longer being used. Now cleaned.
https://github.com/atutor/ATutor/commit/4966819c57fa2bc7b838d8f40b0f9197c6c7b0fd
