### ISSUE TITLE
downloaded file from atutor.ca shows this error

### ISSUE THREAD

**Issue by akehsanz** [atutor/ATutor#132]
This fatal error can be quite discouraging for newcomers of this software...
Fatal error: Call to a member function fetch_array() on boolean in F:\xampp\htdocs\atutor\include\lib\mysql_connect.inc.php on line 153
--I don't seem to figure out why this error is popping out??
But, the STRANGEST THING is that:
the github file when installed & run, doesn't show this error.
*********************************
Still I want to know why this error (as solving errors is good) is showing??
my Action: I've merged the github 'mysql_connect.inc.php' file to the atutor.ca file, but no work yet !!

**Comment by atutor** [comment]
My guess is the files were corrupted when unzipped or uploaded to the server. Upload the tar.gz package to the server, and unpack it there.

Others are not reporting this issue.
