### ISSUE TITLE
There are no languages installed!

### ISSUE THREAD

**Issue by ScriptPup** [atutor/ATutor#133]
A fresh ATutor installation succeeds, but when I try to access the login page the only message displayed is the one listed in the title above. (There are no languages installed!)

I checked the language table and language_text table, they're both populated. The language table has only en, and the language_text table has plenty of en keyed rows.

The environment is:
Win10
IIS8
PHP7.1.7
MySQL 5.7.19
There is no public access address to provide, as this is a local test instance to decide whether Atutor will work for our needs.

I debugged a little, but was unfortunately able to figure out what was going on without spending more time than I have. PHP errorlog attached.
[PHP71x64_errors.zip](https://github.com/atutor/ATutor/files/1242797/PHP71x64_errors.zip)

**Comment by atutor** [comment]
There's no support for PHP7 yet. Switch to a recent version of PHP5

**Comment by ScriptPup** [comment]
Doh! That did it, thank you.
