### ISSUE TITLE
Two 'case' with same condition

### ISSUE THREAD

**Issue by AppChecker** [atutor/ATutor#138]
Hi!
Please look this [fragment](https://github.com/atutor/ATutor/blob/4966819c57fa2bc7b838d8f40b0f9197c6c7b0fd/mods/_core/imsqti/classes/QTIParser.class.php#L123):

```
switch($name) {
...
			case 'setvar':
				$this->attributes[$this->item_num][$name]['varname'] = $attributes['varname'];
				break;
....
			case 'setvar':
				$this->attributes[$this->item_num][$name]['varname'] = $attributes['varname'];
				$this->attributes[$this->item_num][$name]['action'] = $attributes['action'];
				break;
...
}

```
It's suspicious that  'setvar' is checked twice.

---
This possible defect found by [AppChecker](https://npo-echelon.ru/en/solutions/appchecker.php)
References:
[CWE-561: Dead Code](https://cwe.mitre.org/data/definitions/561.html)

**Comment by atutor** [comment]
It does look suspicious. Though its been like this for many years, and does not seem to have created problems. We'll leave this as an acknowledged issue, and if the opportunity arises to test and fix, we'll take a closer look.
