### ISSUE TITLE
Atutor 2.2.2 installation issue step 3

### ISSUE THREAD

**Issue by vedranvucic** [atutor/ATutor#139]
I tried to install ATutor 2.2.. The first step is passed with green checkmarks, PHP 5.6.32, MySQL 4.1.10, . In second step I put name of database, user name and when I move forward to step 3. I have on screen only Atutor blue header with text Atutor 2.2.2 installation and nothing happens.

Please advise

**Comment by atutor** [comment]
Refer to the system's php_error.log for clues

**Comment by vedranvucic** [comment]
I tried fix
https://github.com/atutor/ATutor/commit/0f5c18453a0e0d39c857e9c1079e0ea384af5d90
but it did not work.
I checked error part of cpanel and there are no messages in it.

**Comment by atutor** [comment]
cpanel does not have a php_error.log. You'll probably need to login to a command prompt to find it. and it may need to be enabled in the system's php.ini file. Ask a sysadmin to help you enable it.

**Comment by vedranvucic** [comment]
On this pastebin you can see PHP errors.
https://pastebin.com/DpzNneQ3

**Comment by atutor** [comment]
Which version of ATutor exactly did you download (2.2.2 or 2.2.3b2)? Where did the download come from?

These error messages suggest mysqli is not available, which is strange since php5.6 should have it by default. Try generating a phpinfo() page to output your php settings, like the following.

<?php
phpinfo();
?>

**Comment by atutor** [comment]
Apparently can't post a php snippet here. Create a php file with the following line in it 

phpinfo();

**Comment by vedranvucic** [comment]
Hello, It is version 2.2.2 downloaded from atutor.ca.
I contacted hosting company to check whether mysqli is available or not.

**Comment by vedranvucic** [comment]
I changed hosting company and in step 3 I have got the following message:
Fatal error: Call to a member function fetch_array() on boolean in /home/bastono/edu/ATutor/include/lib/mysql_connect.inc.php on line 153
Please advise.

**Comment by atutorlangs** [comment]
If you have an option to upgrade to a new version of mysql, that may help. Mysql 5.0.1 to 5.6 should work well (but not Mysql 5.7). Also be sure you're not using the MariaDB replacement for MySQL, which is not fully compatible with ATutor.

If its still a problem after upgrading mysql, you'd need to do some debugging to determine the issue, using the debug() function to output variable values to determine where things are failing. See details at:
https://atutor.github.io/developer/guidelines.html#hl_1973 

I am gradually retiring from ATutor over the next 6 months, and moving everything onto github where it will be left as public domain software. As of July, after 15+ years, I will no longer be providing general user support. I will only continue providing developer level support into the future. My suggestion is to make friends with, or hire, someone who has PHP/Developer experience.

**Comment by atutor** [comment]
resolved in the latest nightly build
