### ISSUE TITLE
File manager does not retrieve upload imagenes

### ISSUE THREAD

**Issue by davidand182** [atutor/ATutor#144]
Hi everyone.
I am novice in ATutor and my first language is not English. 

This is the only place i found to ask  for help. If not, I apologize. 

I am experiencing a problem when editing a new course. When I am trying to upload a image using File Manager, the image is successfully uploaded however the file is not accesible in preview view. The link reads something like /atutor/get.php/filename.png As result, I can't use any file uploaded in my course.

For example the links reads:
http://localhost/atutor/get.php/filename.jpg
However, the imagen is located(The file was successfully uploaded) in the next directory:
define('AT_CONTENT_DIR', 'C:\\xampp\\htdocs\\atutor\\content\\\\');

I used XAMPP to install ATutor in Windows, the features are:

ATutor Version: 2.2.3(unknown - 2018-01-17 19:55:56). Check Latest Version.
PHP Version: 7.1.12
MySQL Version: 10.1.29-MariaDB
OS: Windows NT 6.1

Feel free to answer me.

**Comment by atutor** [comment]
That looks like a bug. Thanks for pointing it out. 

I'll try to take look at it in a few days

**Comment by atutor** [comment]
It turns out what I was seeing was another problem.

The get.php file in the path is correct if AT_FORCE_GET_FILE is set to TRUE in the include/config.inc.php file. You could try setting that value to FALSE and see if that helps.

Also, the content you are working with, did you import it, or did you create it in ATutor?

**Comment by davidand182** [comment]
Thanks a lot!!!
Your advice was the solution: _AT_FORCE_GET_FILE is set to FALSE_

Note: I didn't import the conten in ATutor. I created in ATutor completely blank page.

Best regards.
