### ISSUE TITLE
Level headings 

### ISSUE THREAD

**Issue by davidand182** [atutor/ATutor#145]
Hello everyone

I`m trying to provide descriptive headings in the text editor so I` am using the  **format** option for **level heading**: Header 2, Header 3, ....., and paragrah

My problem: In the visualization of the content, the _Page Contents area_ don`t show correctly the html code (levels and paragrahps).

I atach the pictures to describe the error.

Thanks a lot for help me.

Image 1: HTML Code
![html_code](https://user-images.githubusercontent.com/35540112/35240375-3a4a8ff4-ff81-11e7-82b3-2b37dcb16069.png)

Image 2: Visualization Page Content area (Not Ok - it is my problem)
![page_content](https://user-images.githubusercontent.com/35540112/35240376-3a726132-ff81-11e7-9467-bbf588799709.png)

Image 3: Visualization Body area (Ok)
![page_body_content](https://user-images.githubusercontent.com/35540112/35240450-7fb604c4-ff81-11e7-93f0-10ad65517ebf.png)

**Comment by atutor** [comment]
Which version of ATutor are your using?

**Comment by davidand182** [comment]
Hello,
The version is: ATutor 2.2.2
 XAMPP 5.6.33: Apache 2.4.29, MariaDB 10.1.30, PHP 5.6.33

**Comment by atutor** [comment]
The problem appears to be fixed in 2.2.3 (soon to be released), though the bug report is still open:
http://www.atutor.ca/atutor/mantis/view.php?id=5801

After making a backup copy of /include/lib/output.inc.php, I would suggest replacing it with a current copy from Github:
https://raw.githubusercontent.com/atutor/ATutor/master/include/lib/output.inc.php

Let me know if that works, so we can resolve the bug. thx

**Comment by davidand182** [comment]
Hi.
It doesn’t work for me
If you have another suggestion I would really appreciate it

**Comment by atutor** [comment]
Cindy may be able to help with this. It seems to be a regular expression issue, which seems to be matching more than headings.

``` 
preg_match_all("/<(h[\d]+)[^>]*>(.*)<\/(\s*)\\1(\s*)>/i", $content, $found_headers, PREG_SET_ORDER);
```
https://github.com/atutor/ATutor/blob/c3b76d0443ca560b3df46bda65d3fa4f8db51728/include/lib/output.inc.php#L1028

thanks Cindy.

**Comment by cindyli** [comment]
@atutor, I issued a pull request https://github.com/atutor/ATutor/pull/146 for this issue.

**Comment by atutor** [comment]
Here's the fix:
```
preg_match_all("/<(h[\d]+)[^>]*>(.*?)<\/(\s*)\\1(\s*)>/i", $content, $found_headers, PREG_SET_ORDER);
```

**Comment by davidand182** [comment]
Thanks a lot.
I tried it and worked perfectly!!!.

**Comment by atutor** [comment]
Good to hear.
