### ISSUE TITLE
Error deleting/remaning files

### ISSUE THREAD

**Issue by davidand182** [atutor/ATutor#148]
Hi everyone.

I upload some files (pictures *.png, *.jpg) through file manager.

The problem: I can not delete or rename these files. I atach the images to support it.

I am using:

ATutor 2.2.2
XAMPP 5.6.33: Apache 2.4.29, MariaDB 10.1.30, PHP 5.6.33

1) Delete file  YES/NO

![delete_yesno](https://user-images.githubusercontent.com/35540112/35345010-7f2d9d38-00fc-11e8-8d7e-befe164021c4.png)

2) Error message

![delete_errormessage](https://user-images.githubusercontent.com/35540112/35345024-845f2e7a-00fc-11e8-870e-dc923287a84a.png)

**Comment by atutor** [comment]
I'm not able to reproduce the problem myself. If you want to try debugging, see how the debug() function is used:
https://atutor.github.io/developer/guidelines.html#hl_1973

Start debugging somewhere around where the error messages are generated:
https://github.com/atutor/ATutor/blob/master/mods/_core/file_manager/delete.php#L46

If you are on a shared host, I have seen occasions where hosts do updates that end up removing write permissions on the ATutor content/ directory. Perhaps check with you host and see if there have been any recent updates etc.

**Comment by davidand182** [comment]
I understand. 

I know very little about how to debug php files. My purpose is to create an Open Educational Resources(OER) without advance knowledges about program language. 

Thanks for answering!!! Have a nice day!!!
