### ISSUE TITLE
problem in farsi language pack

### ISSUE THREAD

**Issue by fathianf** [atutor/ATutor#149]
Hi. I have upgraded from ATutor 2.1.1 to ATutor 2.2.2 and installed atutor-2-2-2-fa as a second language. But my farsi courses are not showing correctly. I also change my database charset to utf8 with no change. Would you please let me know what should I do as most of our courses is in farsi language and converting them manually is so hard and time consuming.

**Comment by atutor** [comment]
What do you mean by not showing up correctly?
What version of PHP, MySQL, Browser?

If you were upgrading from 2.1.1, the database should have already been UTF-8. So, its hard to say why your content is no appearing correctly.  There would have been no change to the database character set with this upgrade. I would suggest returning to a backup and trying again.
