### ISSUE TITLE
Atutor can't login

### ISSUE THREAD

**Issue by molorane** [atutor/ATutor#150]
Atutor can't login using other browsers except chrome on my mac. I can only login using google chrome. Other browsers such as safari, firefox are not working at all. Also i can't login with more than one users at the time. I am running Atutor version 2.2.3.

**Comment by atutor** [comment]
Clear your browsers' cache, and delete any ATutor related cookies from you browser. 

You can login with multiple users using private browsers windows, or by using different browsers.

**Comment by molorane** [comment]
I did, but i still experienced the same problem. Hurting, when i was about to start trusting Atutor then boom! it disappoints me!

**Comment by atutor** [comment]
I'd say don't jump to conclusions. 

These types of problems are usually browser related. It's not a problem others are having, so I suspect there's something about your setup that's causing your troubles.

First describe what ATutor is running on:
php version
mysql version
webserver version
browser version
operating system

Can you reproduce the problem on the demo site?
https://demo.atutorspaces.com/
login:demo
password:demo
