### ISSUE TITLE
Can't Create a course

### ISSUE THREAD

**Issue by molorane** [atutor/ATutor#151]
Hello sir, the system is working fine on my local machine, but after hosting it online, i am experiencing this error when i try to create a course. Other actions such as updating profile, creating categories i am able to perform them, but when i create a course, i get the error!

"Forbidden
You don't have permission to access /mods/_core/courses/admin/create_course.php on this server.
Additionally, a 403 Forbidden error was encountered while trying to use an ErrorDocument to handle the request."
![screen shot 2018-02-07 at 12 27 54 pm](https://user-images.githubusercontent.com/12952798/35911581-e430d45a-0c02-11e8-99d4-afc64b0b0bc5.png)

**Comment by atutor** [comment]
I'm not able to reproduce the problem. Please describe the system ATutor is running on, and any changes you made to settings both on the server, and in ATutor.

**Comment by molorane** [comment]
I edited the install.inc.php inside Atutor/include/install/install.inc.php to be like this. Only then was i able to install it on the online server. It couldn't pass the step and kept on saying the database is not in utf8_generic_ci, run ALTER... query to change database mode. I did run the query and it was successfully executed, but that didn't help, the error kept coming up. until i have to find a way to overcome the problem by changing the following two lines of code 

$sql2 = 'ALTER DATABASE '.$db_name.' DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci';
$result2 = queryDButf8($sql2, false, false, true, $db);

After successfully installing it, another error is coming up when i try to create a course.
To check the error for your self, visit the demo i hosted online with the following login credentials.

URL: http://jmc.rainbowtrainingcenter.co.za/
Username: blessy
Password: 1

then try to create a course and see the error you will get. The courses that you see there, i exported data from AT_courses in my localhost database and imported it online.

**Comment by gregrgay** [comment]
It's difficult to help not know what ATutor is running on. What OS, Which PHP, webserver, mysql and their respective versions.

My guess is file permissions have been changed. This would not be an ATutor related issue, but rather a server setting. I'd suggest reviewing the permissions of that particular file, as well as its parent directory to be sure they are both readable by the web server.

**Comment by molorane** [comment]
I actually checked the permissions as you mentioned. try to change but that didn't help
![screen shot 2018-02-08 at 5 05 48 pm](https://user-images.githubusercontent.com/12952798/35980019-60bcd808-0cf2-11e8-80ea-6236a9d7386c.png)

**Comment by gregrgay** [comment]
Have your system administrator take a look, or contact your service provider for help. This is a server issue rather than an ATutor one.
