### ISSUE TITLE
about Atutor installation

### ISSUE THREAD

**Issue by ruanyichen** [atutor/ATutor#153]
when the installation go to the step 1,I choose the button "I agree".But there is a blank page on the screen.What should I do? By the way ,on the step 0,all the condition have been satisfied

**Comment by atutor** [comment]
View the PHP error log for hints.
What version of ATutor?
What PHP version?
What MySQL version?

**Comment by ruanyichen** [comment]
atutor 2.2.2
php5.6.34
mysql5.6.16

**Comment by ruanyichen** [comment]
Call to a member function fetch_assoc() on a non-object in /var/www/html/ATutor/include/lib/mysql_connect.inc.php on line 308, referer: http://202.116.46.251/ATutor/install/install.php

**Comment by atutor** [comment]
Is there a slash "\" in the mysql password? 
The password may need to be change if there is.

**Comment by ruanyichen** [comment]
Thanks!My problem has beens solved!By the way,I want to know that teachers can track the situation of students'study?

**Comment by ruanyichen** [comment]
Thanks!My problem has beens solved!By the way,I want to know whether the  teachers can track the situation of students'study?

**Comment by atutor** [comment]
What did you do to solve the problem?

Yes, teachers can track students' progress using the tracker. See the Handbook for details.

**Comment by ruanyichen** [comment]
I think there are something wrong with mysql.When I stall mysql again and change my password,I can install ATutor successfully.There are also a slash "\" in my last password.Beside the progress, can the teachers track the students' learning situations，for example the learning time.

**Comment by ruanyichen** [comment]
I think there are something wrong with mysql.When I stall mysql again and change my password,I can install ATutor successfully.There are also a slash "\" in my last password.Beside the progress, can the teachers track the students' learning situations，for example the learning time?
