### ISSUE TITLE
Fresh install NoGo

### ISSUE THREAD

**Issue by larrykh465** [atutor/ATutor#157]
I just tried a fresh install of 2.2.4
Debian 8     MYSQL client api ver 5.5.60  MYSQLI client api ver 5.5.60  
pdo_mysql  client API version | 5.5.60

The following errors occurred:
ATutor was unable to access the database. If the problem persists, please report this to an Administrator with this date reference (08/04/2018 05:23:52 am ) 

The install script completed successfully and the database tables were all successful.
tried twice, first time setting database up with  atutor as user p/w and again via root user   same result.
letting you know

**Comment by gregrgay** [comment]
Unable to reproduce any errors during install.
