### ISSUE TITLE
Atutor 2.2.4 module install issue

### ISSUE THREAD

**Issue by haseeb200** [atutor/ATutor#162]
I have recently downloaded ATutor 2.2.4 and installation went successfully. There were no errors. Now as an admin I want to install scorm_package module to support scorm courses. I downloaded the package from ATutor website and try to install it. I got the following errors every time when I hit the **install** button. 

![capture](https://user-images.githubusercontent.com/10439778/47938981-8b526c80-df07-11e8-979d-62248125d1d0.PNG)

How to solve this error?

**Comment by atutor** [comment]
That module is a third party module that has not been maintained. It would need to be reviewed and updated before it would work with 2.2.4.

**Comment by haseeb200** [comment]
what about other packages like openmetting? I have also tried to install that but that's also giving me the same error

**Comment by haseeb200** [comment]
Is there any way I can upload scorm courses without the third-party module? DOes ATutorsupport scorm 1.2 without any 3rd party package?

**Comment by haseeb200** [comment]
@atutor any thoughts on this?
