### ISSUE TITLE
installation issue 2.2.4 ATutor

### ISSUE THREAD

**Issue by vedranvucic** [atutor/ATutor#163]
I tried to install ATutor 2.2.4 on shared hosting and I have got teh following error messages:
Warning: Invalid argument supplied for foreach() in /home3/slobodan/public_html/atutor/include/lib/mysql_connect.inc.php on line 138

Warning: mysqli_result::fetch_array() expects parameter 1 to be integer, string given in /home3/slobodan/public_html/atutor/include/lib/mysql_connect.inc.php on line 159

Warning: mysqli_result::fetch_array() expects parameter 1 to be integer, string given in /home3/slobodan/public_html/atutor/include/lib/mysql_connect.inc.php on line 167
I have also received message that databse is not utf8 which I corrected by entering SQL query. When I Am prompted to enter SQL query to change characterset I entered to SQL query but I am prompted always that it is needed to change characterset by installation process of ATutor. Please advise

**Comment by atutor** [comment]
Hi Vedran, ATutor is not longer being supported.
