### ISSUE TITLE
Stored XSS in "Real Name" field - My Account

### ISSUE THREAD

**Issue by SegfaultMasters** [atutor/ATutor#164]
**Description -**
There's no escape being done before printing out the value of `Real Name` in the My Account page.

**ATutor version -** v2.2.4

**Steps to reproduce -**

- Navigate to http://localhost/atutor/mods/_core/users/admins/my_edit.php & add the below-shared payload as the value to the Real Name field.
   Payload -`admin<img src=xss onerror=alert(1)>`

- Visit page http://localhost/atutor/mods/_core/users/admins/index.php, the payload will be triggered.

![image11](https://user-images.githubusercontent.com/2347778/51242136-44700100-19a5-11e9-892e-5f1e8dba7dcb.jpg)

![image6](https://user-images.githubusercontent.com/2347778/51242140-46d25b00-19a5-11e9-8df4-66a68f78cfa6.jpg)

**Comment by atutor** [comment]
Please submit a pull request to fix this.

**Comment by fgeek** [comment]
> Please submit a pull request to fix this.

As a maintainer of this project are you planning to fix this and release new version? I don't think waiting for PRs is correct way to handle security issues (maybe only if this is mentioned clearly in some documentation). Of course that is only my personal opinion, but I can't recommend people to use ATutor if this is the case.

**Comment by atutor** [comment]
ATutor is no longer maintained.
