### ISSUE TITLE
Error 500 when install any new module

### ISSUE THREAD

**Issue by HoanNhi** [atutor/ATutor#168]
Hi, so I tried to install openmeeting and certify modules, but whenever I had uploaded these zip files through GUI module installation of Atutor, pressed Yes to install and things started to go wrong.
Here is the screenshot:
![Screenshot (13)](https://user-images.githubusercontent.com/49232230/61185891-a4abdb00-a688-11e9-812a-d275f350ec64.png)
![Screenshot (12)](https://user-images.githubusercontent.com/49232230/61185894-aa092580-a688-11e9-96f0-16e3d030d5fd.png)

I hope that this will be previewed and helped as soon as possible. Thank you very much

**Comment by atutor** [comment]
This module has not been updated in a very long time, and it's no longer being maintained. It may be fixable by someone with php experience, updating for php 7+.

**Comment by HoanNhi** [comment]
> This module has not been updated in a very long time, and it's no longer being maintained. It may be fixable by someone with php experience, updating for php 7+.

So can you help me to fix this code in PHP? Thank you very much

**Comment by atutor** [comment]
You'll need to find someone else. ATutor is no longer being maintained.
