### ISSUE TITLE
Unable to use Atutor Demo

### ISSUE THREAD

**Issue by locipicol** [atutor/ATutor#172]
Hello,

When login to Atutor 2.2.4 Demo at https://atutor.github.io/atutor/demo.html it returns me an error 405 Not Allowed.

Best regards.

**Comment by gregrgay** [comment]
Unfortunately that demo is not longer available. You could try Softaculous
https://www.softaculous.com/demos/ATutor

**Comment by locipicol** [comment]
Thank you but it seems the demo is unavailable on Softaculous too (error 404).

**Comment by gregrgay** [comment]
Click on the Admin Panel link at the top

**Comment by locipicol** [comment]
It worked, thank you.
