### ISSUE TITLE
Cómo hago esta configuración? Ayuda, Please.

### ISSUE THREAD

**Issue by ejrmjuan** [atutor/ATutor#174]
Buenas noches, un placer saludarles. La presente es para comunicarles que realice todos los pasos de instalación de Atutor 2.2.4 y al final cuando inicio sesión como administrador me sale este mensaje: La configuración del correo no está configurada correctamente. Es posible que no pueda enviar correos electrónicos. Quisiera que me orientaran por favor para solucionar este problema, muchas gracias de antemano.

**Comment by atutor** [comment]
https://atutor.github.io/atutor/docs/faqs.html#1
