### ISSUE TITLE
"Debugging boxes" showing on atutor 2.2.4

### ISSUE THREAD

**Issue by OrbisTerrarumProLiberi** [atutor/ATutor#175]
![1](https://user-images.githubusercontent.com/43192310/78805568-24868c00-79f4-11ea-9f37-f3d54d7143bc.png)

See attached files, thanks!

**Comment by gregrgay** [comment]
At the top of include/vitals.inc.php file change "1" to a "0" for :
define('AT_DEVEL', 1);

**Comment by OrbisTerrarumProLiberi** [comment]
Thanks a lot @gregrgay
