### ISSUE TITLE
I can't install the ATutor database on ubuntu 20.04

### ISSUE THREAD

**Issue by gaositd** [atutor/ATutor#178]
![atutor](https://user-images.githubusercontent.com/65265850/81767965-5a111000-949f-11ea-9cc2-1c01014a88b9.png)
Hi, everybody.

I'm installing ATutor on a virtual machine with Ubuntu Server 20.04, I got an error with UTF8, I checked a previous thread but it doesn't give the solution to the problem, can you help me please?

I made the database with code, it didn't work, I created it with PhpMyAdmin, it didn't work either, in both cases the database was created successfully, I send you the images, of the error and the creation of the database with PhpMyAdmin.
The Server version: Apache/2.4.41 (Ubuntu), Server built:   2020-04-13T17:19:17
The mysql  Ver 8.0.20-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))

Regards
![phpmyadmin](https://user-images.githubusercontent.com/65265850/81767898-2930db00-949f-11ea-994d-c950de8a54fc.png)
![atutor](https://user-images.githubusercontent.com/65265850/81767900-2afa9e80-949f-11ea-9f04-f735391a9c4b.png)

**Comment by Manjuphoenix** [comment]
Don't create the database before installation, the LMS will create its own new database with name atutor
I faced the same issues couple of hours back, i deleted the database i had created manually on mysql, later which it started working fine

Its very outdated response but i hope it helps someone in future
