### ISSUE TITLE
Upgrade requirements

### ISSUE THREAD

**Issue by banderson407** [atutor/ATutor#181]
I have a Atutor 2.1.1 installation and want to upgrade to 2.2.4
Are there any requirements that I need to be aware of?
Can I jump right to 2.2.4 or do I have to do incremental upgrades 2.2=>2.2.1=>2.2.2=>2.2.4?
Are there any new settings needed in php.ini ?

**Comment by gregrgay** [comment]
I don't recall the exact requirements for 2.1.1. You'll want to upgrade PHP to 7.0+, and probably Mysql to 5.6/5.7. Be sure to take a backup before doing anything. Full requirements are listed at: https://atutor.github.io/atutor/docs/requirements.html

**Comment by banderson407** [comment]
Thanks Greg,
I have PHP 7+ and Mysql 5.6 running on the the test account so I guess I will try to jump directly to 2.2.4 this weekend and see how it goes.
Brad

**Comment by banderson407** [comment]
Greg,

After the upgrade I am getting the following error:
ATutor was unable to acces the database. If the problem persists, please report this to an Administrator .......

**Comment by gregrgay** [comment]
Perhaps a mysql permissions issues. Your DB user needs alter table privilege.  

See:
https://atutor.github.io/atutor/docs/installation#upgrade
or:
https://atutor.github.io/atutor/docs/requirements.html

You could also review the php error log for clues.

**Comment by banderson407** [comment]
Greg,
THe DB user had privileges but I change it to the MySql admin user just to check and still the same issue.
Not sure about the php.ini setting, maybe I have something missing there. I'll send the current setting to your gmail address (if oyu don't mind) so you can take a look and see if I'm overlookng something.
Also have an issue with a local module but pretty sure it is tied to this DB issue as well.

thaks
Brad

**Comment by gregrgay** [comment]
It would seem you're using php's FastCGI version. ATutor was built around the mod_php version. You could try installing php as an Apache module.  Also, review your php/mysql error logs. https://www.php.net/manual/en/security.apache.php

**Comment by banderson407** [comment]
Greg,

While looking at the error log file it seems that I am missing a table (users_online). It is also missing from my production account??
There were no errors during the upgrade but also no reference to that table either.
How is the best way to rectify this and maybe get one step closer to a clean upgrade?

Thanks
Brad

**Comment by gregrgay** [comment]
Strange. users_online has been part of ATutor since the beginning and has not changed. If you have access to something like phpMyAdmin, you could run the SQL to create the table, being sure to add/adjust the table prefix in the SQL(e.g. AT_ ).  https://github.com/atutor/ATutor/blob/master/include/install/db/atutor_schema.sql#L1044

**Comment by banderson407** [comment]
Greg,

That eliminated the SQL error. Yeah, that is odd that it was missing from both sites (production and test). There is no error generated to the screen so no telling how long it has been gone.

Now I just have to work on the local module and then the test account should be done and ready to start planning the production upgrade.

Thanks, I'm sure we will talk more
Brad
