### ISSUE TITLE
Error while instlling

### ISSUE THREAD

**Issue by ESPPRA** [atutor/ATutor#182]
Trying to install ATutor but getting 2 errors.
1) . in include_path | Disabled
2) Javascript Enabled? | Disabled

![Atutor](https://user-images.githubusercontent.com/66976724/84711939-bc11d900-af67-11ea-9f58-7e28098eb71a.PNG)

**Comment by gregrgay** [comment]
In the system's php.ini file add a "." to the include_path variable
e.g.  include_path = ".;c:\php\includes"

Here's a few more ways:
http://www.geeksengine.com/article/php-include-path.html

The Javascript error usually occurs when the browser's Javascript is disabled, but it might be a hung script. Try restarting the browser.
