### ISSUE TITLE
ATutor 2.2.1 Doesn't Detect MySQL on Ubuntu 16.04 with PHP 7 and MySQL 5.7

### ISSUE THREAD

**Issue by t3chn0t3s** [atutor/ATutor#183]
I understand that ATutor is no longer supported and that version 2.2.1 is not the most recent version, but I was hoping to get this particular version setup.  I've was able to get beyond the installation process using Ubuntu 14.04, but later encountered errors related to the database.  

Hoping to resolve these I attempted the install on Ubuntu 16.04.  I now encounter a problem when I try to start the installation process.  ATutor shows a failed status for mysql and MySQL 4.1.10+ and as a result I'm not allowed to continue.  See below.

![image](https://user-images.githubusercontent.com/46801776/87499833-c388d880-c620-11ea-95f3-3cb37224e998.png)

As you can see from the screenshot PHP 7.0.33 is installed.  I also confirmed that I had both the mysql-client and server packages installed.  See below.

![image](https://user-images.githubusercontent.com/46801776/87500020-29756000-c621-11ea-9067-3fd03a6ef6b4.png)

I found one article that described a defect in version 2.2.2 that required that line 462 on /var/ww/html/atutor/include/install/install.inc.php be modified so that it ended up being "**$row = queryDButf8($sql, $db_name, true, true, $db);**".  I did make that change, but it did not correct my issue. I welcome any suggestion any of you may have to get this issue resolved.  Thank you for your time and efforts.

**Comment by acli** [comment]
Do you have the `php7.0-mysql` package installed? This is the glue that binds MySQL and PHP together

**Comment by gregrgay** [comment]
MySQl 5.7 support was not available until V2.2.4. Refer to the system requirements at https://atutor.github.io/atutor/docs/requirements.html

**Comment by t3chn0t3s** [comment]
Thank you very much for informing me of that and providing the link to the requirements.  I see some other potential problems noted with the requirements that I'll need to address.
