### ISSUE TITLE
Test scores/marks not showing

### ISSUE THREAD

**Issue by banderson407** [atutor/ATutor#186]
Greg,

Not sure if you meant to say for tests with only one attempt the marks won't show or that hey would.
I tried taking a test two times and marks still not showing?

Brad

**Comment by gregrgay** [comment]
I meant, in the test's properties attempts need to be set to 1. With 3 attempts it is recognized as an unmarked self test.

**Comment by banderson407** [comment]
I'm a bit confused, I know what's new.
We have always had the number of attempts set to 3 and the score has shown.  see example.
Is this something new, I didn't start seeing it until I upgraded from 2.1.1 to 2.2.4
Brad
 
<img width="1645" alt="Screen Shot 2020-09-22 at 11 02 37 AM" src="https://user-images.githubusercontent.com/66698327/93920482-19829800-fcc4-11ea-800f-11d8ff834c2f.png">

**Comment by gregrgay** [comment]
I do not recall the exact circumstance, but it has been that way for a while. My recollection is a bit fuzzy these years later.

Given its a module you're working on though, I would think you could program your way around that.

**Comment by banderson407** [comment]
You sound like me.
If it is running the way it is suppose to  I can live with it unless I get some complaints from return students.
It doesn't affect the certificate module since I am only looking at highest score per test and time spent in content.

This is the part of an upgrade that I hate, everything that comes up I have to wonder if it's an issue with code, PhP version or something else completely.

I spent so much time getting the code I was working on solid and didn't worry about what may have changed in Atutor.
A lot of it is a guessing game at the moment. For example, depending on the version of PhP I choose (7.3.11 Fast CGI Stable, 7.3.11 CGI stable or 7.3.11 Latest) the time spent on a test can be logged as 3m or 1147hours????

Have been kicked out and back to the login screen a couple times as well without an error generated??
Like I said, I hate this part of an upgrade.

But on the bright side, the certificate module is running flawlessly so far.

**Comment by banderson407** [comment]
Now what is odd is the in the TST account the Marks show (tested just now) but not in the live account.
Both were upgraded from 2.1.1 to 2.2.4 and same version of PhP???
Do you if the Atutor code is updated or if patches are maintained anyplace?

Brad

**Comment by gregrgay** [comment]
Strange. 2.2.4 has no patches, though there have been a few tweaks people have submitted to the repo in Github if you happen to be working from a GitHub clone.  You could scan the commit history.

If you're woring with the bundled 2.2.4 in both cases, they should be the same, apart from any settings differences between the two.

**Comment by banderson407** [comment]
Yeah, very strange.
Pretty sure I installed both from the same file I downloaded from GitHub
Another question.

Starting today I've noticed some files building up in the tmp directory from the production account installation.
They look like attachment. Any idea what they are?

Brad
<img width="1142" alt="Screen Shot 2020-09-22 at 12 45 06 PM" src="https://user-images.githubusercontent.com/66698327/93929999-894b4f80-fcd1-11ea-9343-80f1070b10a5.png">

**Comment by banderson407** [comment]
It looks like user preferences from Author but not sure and why store it there?

**Comment by gregrgay** [comment]
That's normal. They are PHP session files. They will be deleted by PHP garbage collection based on the interval set in session.gc_maxlifetime in the php.ini file.

**Comment by banderson407** [comment]
Thanks, second guessing myself again.
Would a re-upgrade gain me anything at this point?
What lead me to the Sees files was a some errors from a few days ago saying it needed a ssl path to get to the file manager folder??
Still having an issue with getting kicked back to the login screen with no error being logged?? any thoughts?

**Comment by gregrgay** [comment]
Check your timeout setting, in the ATutor user's preference settings.
or
It might be cache related. Dump your browser's cache. Try a different browser etc.

**Comment by banderson407** [comment]
Greg,

Tried those but tried them again and just now when I logged in as an administrator and chose the course to view it dumped me to the login for that course instead of dropping me into the course as the instructor.
When I tried it the second time it worked???
There were no errors logged. Is there a way to force an error just to make sure it is logging errors?

Thanks
Brad

**Comment by banderson407** [comment]
Forgot to mention, had a student email me last night to say they were getting kicked out frequently.
Without errors, do you know of anyplace I can't look to resolve?

**Comment by gregrgay** [comment]
See if the solution mention here helps:
https://atutorlangs.github.io/atutor/archive/t-22595.html

**Comment by banderson407** [comment]
Greg,

Thanks,that help me with my issue.
Didn't seem to help the student but I do believe the issue is on their end,

Thanks for your help
Brad
