### ISSUE TITLE
Test showing no questions available

### ISSUE THREAD

**Issue by banderson407** [atutor/ATutor#187]
Greg,

Have another one.
Had a student say they can't take a test because it shows no questions available.
When I try the test I don't have that problem
When looking at her entries in the tests_results file I see a status of 0 for the test and others show a status of 1.
What does the status refer to?
Also if need be can that entry just be deleted or will it cause issues?

Thanks
Brad

**Comment by gregrgay** [comment]
I'd need to investigate to find answers, so I'll leave that to you. I don't have any quick suggestions.

**Comment by banderson407** [comment]
I've looked in the online administrator documentation but can't find a data dictionary.
Y'all must have created one when developing the program, do you know if it was ever published?

**Comment by gregrgay** [comment]
There's an old db schema in the Developer doc. Probably not all that useful (V1.4.1). Was never really maintained. 
https://github.com/atutor/ATutor/blob/master/documentation/developer/database.gif

Most of what you need to know about the data can be deduced from atutor_schema.sql
https://github.com/atutor/ATutor/blob/master/include/install/db/atutor_schema.sql

**Comment by gregrgay** [comment]
...wait! Here's a more recent schema.
https://github.com/atutor/ATutor/blob/master/documentation/developer/atutor_schema.png

**Comment by banderson407** [comment]
Greg,

Thanks, I know you have better things to do than deal with my issues and I appreciate the assistance.
That certainly gives me a starting point.

Brad

**Comment by banderson407** [comment]
Greg,

Just a quick follow up. 
I couldn't find a reason for the issue but when I removed the entry from tests_results the problem went away and they are able to take the test and complete the course.
Quick question before I close this thread...when a new student registers they see a prompt to edit preferences. They see this every login until the go into the preferences and apply. Is there an option the prevents this from showing?

Brad

**Comment by gregrgay** [comment]
There isn't an option to remove the preferences prompt. But hey, anythings possible with open source if you want to find the code an hack it.
