### ISSUE TITLE
Test with no questions

### ISSUE THREAD

**Issue by banderson407** [atutor/ATutor#188]
Having an issue where a student selects a test and it states there are no questions found.
Going to the previous screen show and error but with no description.

When the instructor selects the same test, there is no issue???

Any idea where to look or how to remedy?

Thanks

**Comment by gregrgay** [comment]
Sorry, nothing comes to mind.

**Comment by banderson407** [comment]
Being it is one of 12 tests and the others seem to work fine, I am thinking of just deleting it and adding it back as a new entry.
My question is : what happens to all the historical data (test results) that are tied to the bad test?
Odd that the test has worked fine for 10+ years util now?

**Comment by gregrgay** [comment]
I'd suggest just disabling the bad test, setting the end date to some time in the past, so students can access it anymore. I don't recall for sure, but would assume the data would be remove with the test, given in order to access that data, you'd need a test ID (i.e. orphaned data without an ID).

**Comment by banderson407** [comment]
Thanks Greg,
That is what I figured but was hoping for something else.

Thanks for the input as always,
Brad
